import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';

import Header from '../../components/nav/Header';
import styles from '../../styles/Home.module.css';
import AddPeople, { OnClickAddProps } from '../../components/people/AddPeople';
import { addPersonToOrg } from '../../libs/firebase';
import useCurrentOrg from '../../libs/store/slices/orgs/useCurrentOrg';
import RoomsList from '../../components/rooms/RoomsList';
import AddRoom from '../../components/rooms/AddRoom';

const Dashboard: NextPage = () => {
  const { org } = useCurrentOrg();
  function onAddPerson({ firstName, lastName, birthday }: OnClickAddProps) {
    if (!org.id) return;
    addPersonToOrg({
      firstName,
      lastName,
      birthday,
      orgId: org.id,
    });
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Chore Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className={styles.main}>
        <h1 className={styles.title}>{org.name} Chores</h1>
        <AddRoom />
        <RoomsList rooms={org.rooms} />
        <AddPeople people={org.people} onClickAdd={onAddPerson} />
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Dashboard;
