import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';

import Header from '../../components/nav/Header';
import styles from '../../styles/Home.module.css';
import AddPeople, { OnClickAddProps } from '../../components/people/AddPeople';
import { useSelector } from 'react-redux';
import { organizationsStore } from '../../libs/store';
import { addPersonToOrg } from '../../libs/firebase';

const Dashboard: NextPage = () => {
  const people = useSelector(organizationsStore.selectors.people);
  const orgName = useSelector(organizationsStore.selectors.name);
  const orgId = useSelector(organizationsStore.selectors.id);
  function onAddPerson({ firstName, lastName }: OnClickAddProps) {
    if (!orgId) return;
    addPersonToOrg({
      firstName,
      lastName,
      orgId,
    });
  }
  console.log(people);

  return (
    <div className={styles.container}>
      <Head>
        <title>Chore Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className={styles.main}>
        <h1 className={styles.title}>{orgName} Chores</h1>
        <AddPeople people={people} onClickAdd={onAddPerson} />
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Dashboard;
